name: test
on: 
push:
  branches: ["main"]
pull_request:
  branches: ["main"]
workflow_dispatch:

jobs:
  build:
   runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v3
  - name: Write a multi-line message
    run: |
      echo This demo file shows a 
      echo very basic and easy-to-understand workflow.
